### ISSUE TITLE
Reserved characters elasticsearch query

### ISSUE THREAD

**Issue by robcza** [intfeed/sinkit-core#21]
There is a problem with unescaped input from IntelMQ resulting in such errors:
http://fpaste.org/244930/40770143/

Inputs has to be sanitized by escaping reserved characters, list is available here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters

Thanks @Karm for reporting

**Comment by kozeltom** [comment]
@robcza http://britts.oharvest.net/v2/cexposer/SIG=1vvc8458h/*http\A\F\Ftm.dp.yieldmanager.net/TagMonkey is this really valid for source.url?

**Comment by robcza** [comment]
Can not really say it isn't. No matter how strange, still a valid URL (the browser will actually encode URL reserved characters according to this https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters)

**Comment by kozeltom** [comment]
I understand the star is valid character. But the whole URL looks strange. It looks like the source feed would aggregate two IoCs together, or the URL would be the type of URL containing the historical URL where user came from.

**Comment by robcza** [comment]
I see, however the source really includes this URL: http://security-research.dyndns.org/pub/botnet/ponmocup/ponmocup-finder/ponmocup-infected-domains-2015-03-23.txt

**Comment by kozeltom** [comment]
The set of reserved characters is wired. For example there is simple slash mentioned but it seems that slash is not a problem (queries with slash or even star are processed without error -> no escaping needed). On the other hand the backslash is a troublemaker, because the logic tries to do some magic with the next character and exception ```JsonParseException[Unrecognized character escape 'A' (code 65) ``` is born. So the conclusion here is, that this is not a problem of reserved characters for Elastic, but problem already in parsing query into Json. I am going to do the escaping of backlash and then we will see.

**Comment by kozeltom** [comment]
closing for now.
